# Configuration for ai_mri_analyzer

[openai]
# API key is now read from environment variable OPENAI_API_KEY (see .env file)
model = "gpt-5"
summary_model = "gpt-5"

[batch]
size = 20

[paths]
results_dir = "results"
reports_dir = "reports" 